pub const STAR_SYSTEM_NAMES: [&str; 196] = [
    "61 Cygni",
    "81 Cancri",
    "Acamar system",
    "Achernar",
    "Adelphous",
    "Ajilon",
    "Akaali system",
    "Alastria system",
    "Alcor system",
    "Aldebaran",
    "Algol system",
    "Alhena",
    "Alpha Centauri",
    "Alpha Doradus system",
    "Alpha Leonis system",
    "Alpha Majoris system",
    "Alpha Omicron system",
    "Alpha Onias system",
    "Altair system",
    "Altamid system",
    "Alvacorn Major",
    "Amar system",
    "Amargosa system",
    "Amleth system",
    "Andorian system",
    "Aneto system",
    "Arakon system",
    "Arcadian system",
    "Archanis",
    "Arcturus",
    "Ardana system",
    "Argaya system",
    "Argelius",
    "Argus system",
    "Atalia system",
    "Avery system",
    "Azati Prime system",
    "Ba'ku system",
    "Bajoran system",
    "Balancar system",
    "Barradas system",
    "Belak system",
    "Benecia system",
    "Benthan system",
    "Benzite system",
    "Berengarius system",
    "Bersallis system",
    "Beta Agni system",
    "Beta Aurigae binary system",
    "Beta Cygni system",
    "Beta Epsilon system",
    "Beta Geminorum system",
    "Beta Lankal",
    "Beta Leonis Minoris",
    "Beta Lyrae system",
    "Beta Magellan system",
    "Beta Mahoga system",
    "Beta Penthe system",
    "Beta Portolan system",
    "Beta Renna system",
    "Beta Renner system",
    "Beta Rigel",
    "Beta Stromgren system",
    "Beta Tauri",
    "Beta Zeta",
    "Bilaren system",
    "Bolarus",
    "Bopak system",
    "Boradis system",
    "Boreth system",
    "Bortas",
    "Braslota system",
    "Breen system",
    "Brestant",
    "Bringloid system",
    "Buruk",
    "C-111 system",
    "Cait",
    "Calder system",
    "Calindra system",
    "Callinon system",
    "Cambra system",
    "Camor system",
    "Camus",
    "Cancri system",
    "Canopus",
    "Capella",
    "Cardassian system",
    "Carraya system",
    "Celes",
    "Cerberus system",
    "Ceti Alpha star system",
    "Chaltok",
    "Chin'toka system",
    "Clarius system",
    "Clarus",
    "Cleon system",
    "Clevari system",
    "Cor Caroli",
    "Cordannas system",
    "Coridan system",
    "Cornelian star system",
    "Corvan system",
    "Cruces system",
    "Cuellar system",
    "Cygnet",
    "D'Arsay system",
    "D'deridex",
    "Darla system",
    "Davlos",
    "Dayos",
    "Delos system",
    "Delphi Ardu system",
    "Delta Rana star system",
    "Delta system",
    "Deneb",
    "Deneva system",
    "Denobula Triaxa system",
    "Dessica",
    "Detrian system",
    "Devidia system",
    "Devolin system",
    "Devron system",
    "Dewa",
    "Dinasia",
    "Diomedian system",
    "Donatu",
    "Dopa system",
    "Dorala system",
    "Dozaria system",
    "Draken system",
    "Dramen star system",
    "Dreon system",
    "Echevarria system",
    "Eightfold Stars",
    "El-Adrel system",
    "Elora",
    "Eminiar",
    "Endicor system",
    "Epsilon Canaris",
    "Epsilon Eridani",
    "Epsilon Indi system",
    "Epsilon Monocerotis",
    "Epsilon Mynos system",
    "Epsilon Nel system",
    "Epsilon Silar system",
    "FGC-347601",
    "Fabrina solar system",
    "Ferenginar system",
    "Fima system",
    "Finibus system",
    "Five systems",
    "Forcas",
    "Fowla system",
    "Frylon system",
    "Galar system",
    "Galen system",
    "Galorndon Core system",
    "Gamelan system",
    "Gamma 400 star system",
    "Gamma 7A system",
    "Gamma Argus system",
    "Gamma Arigulon system",
    "Gamma Eridon",
    "Gamma Hromi",
    "Gamma Hydra",
    "Gamma Tauri",
    "Gamma Trianguli system",
    "Gamma system",
    "Ganalda",
    "Garadius system",
    "Garo VII system",
    "Garth system",
    "Gasko system",
    "Gavara system",
    "Gema system",
    "Ghulion system",
    "Goralis system",
    "Gorath system",
    "Goren system",
    "Gr'oth",
    "Grazer system",
    "Grenna system",
    "Groombridge 34",
    "Gyrannan system",
    "Halee system",
    "Halka",
    "Hanoli system",
    "Kronos",
    "Regal System",
    "Romulus",
    "Sol",
    "System 7743.8",
    "System 892",
    "System D43119",
    "11 Leonis Minoris"
];
