name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install banking app dependencies
      working-directory: ./StarTrek
      run: dotnet restore
    - name: Build star trek app
      working-directory: ./StarTrek
      run: dotnet build --configuration Release --no-restore
    - name: Install star trek app test dependencies
      working-directory: ./StarTrek
      run: dotnet restore
    - name: Test star trek app
      working-directory: ./StarTrekTests
      run: dotnet test --no-restore --verbosity normal
